### ISSUE TITLE
[Easy][Hacktoberfest] Add Awesome - Games tests in Proton

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/Awesome-Proton#3]
See [github.com/TiagoDanin/Awesome-Proton#contribute](https://github.com/TiagoDanin/Awesome-Proton#contribute)

[My other projects - #Hacktoberfest](https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+user%3ATiagoDanin&type=Issues)

**Comment by phoenix1796** [comment]
yes

**Comment by TiagoDanin** [comment]
News?
