### ISSUE TITLE
[Easy][Hacktoberfest] Get Game Name

### ISSUE THREAD

**Issue by TiagoDanin** [TiagoDanin/Awesome-Proton#7]
Get the name of game using your ID (SteamID).

- Use Steam API

[My other projects - #Hacktoberfest](https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+user%3ATiagoDanin&type=Issues)

**Comment by shreyateeza** [comment]
@TiagoDanin Can you please elaborate what exactly is to be done?

**Comment by TiagoDanin** [comment]
@shreyateeza Yes, The [AirMech-Strike-09-29-2018.json](https://github.com/TiagoDanin/Awesome-Proton/blob/master/tests/AirMech-Strike-09-29-2018.json#L5) file has the steam id 206500.
Remove the "name" field and use the Steam API to get the name and other information with the `id`.

-----
Example: Call function `x` ~> input: `206500` ~> return data ~> string: `AirMech Strike` ~> output: `AirMech Strike`.

**Comment by GrayJacketStudios** [comment]
Im on it!

**Comment by TiagoDanin** [comment]
@GrayJacketStudios
- "Remove the 'name' field"
- "Use the Steam API"

**Comment by excalliburbd** [comment]
> * "Remove the 'name' field"

Do you mean the function should delete the `title` filed?

**Comment by excalliburbd** [comment]
@TiagoDanin I have a WIP PR. I can finalize this after understanding what field I should remove and getting an API key for testing

**Comment by TiagoDanin** [comment]
> @TiagoDanin do you mean the function should delete the title filed?
Don't need a function for this... Only removes from all files.

> @TiagoDanin could you provide a api key?
Send via email.

**Comment by excalliburbd** [comment]
@TiagoDanin just to confirm you want the `title` field form `tests/` removed manually right?

**Comment by TiagoDanin** [comment]
@excalliburbd Yes 👍

**Comment by TiagoDanin** [comment]
News?

**Comment by excalliburbd** [comment]
Sorry about the inactivity. I was a bit caught up at work. I'll post an update later tonight :pray:
